"""initial

Revision ID: 2829b50bc034
Revises:
Create Date: 2026-04-03 15:03:07.578588

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2829b50bc034"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_index(batch_op.f("idx_companies_owner"))

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_index(batch_op.f("idx_invitations_company"))
        batch_op.drop_index(batch_op.f("idx_invitations_token"))

    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_index(batch_op.f("idx_memberships_company"))
        batch_op.drop_index(batch_op.f("idx_memberships_user"))

    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_index(batch_op.f("idx_refresh_tokens_user"))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_index(batch_op.f("idx_users_email"))
        batch_op.drop_constraint(batch_op.f("users_email_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_unique_constraint(
            batch_op.f("users_email_key"),
            ["email"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.create_index(batch_op.f("idx_users_email"), ["email"], unique=False)
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_refresh_tokens_user"),
            ["user_id", "revoked", "expires_at"],
            unique=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_memberships_user"), ["user_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_memberships_company"),
            ["company_id", "status"],
            unique=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_invitations_token"), ["token", "accepted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_invitations_company"), ["company_id"], unique=False
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_companies_owner"), ["owner_id"], unique=False
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    # ### end Alembic commands ###
